routes/web.php
<?php

use App\Http\Controllers\Admin\AuthController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Hash;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/login', function () {
//    return view('welcome');
    return redirect('/admin/login');
});
Route::get('/', function () {
//    return view('welcome');
    return redirect('/admin/login');
});
Route::get('/password',function (){
   echo Hash::make('12345678');
});
//Auth::routes(['register' => false,
//    'reset'=>false,
//    'remember'=> false]);


//Route::group(['middleware'=> 'auth'], function(){
Route::get('/accept-payment/{id}',[\App\Http\Controllers\PaymentController::class,'accept_payment']);
Route::get('/cancel-payment/{id}',[\App\Http\Controllers\PaymentController::class,'cancel_payment']);
Route::get('/payment-view',function (){
    return view('payment_response');
});

Route::get('/contact-us',function (){
    return view('users.contact_us');
});

Route::get('/clear', function () {
    Artisan::call('optimize');
});


Route::get('admin/login',[AuthController::class,'showLoginForm'])->name('admin.login');
Route::post('admin/login',[AuthController::class,'login']);
Route::prefix('/admin')->name('admin.')->namespace('Admin')->middleware('auth:admin')->group(function(){
    Route::post('/logout',[AuthController::class,'logout'])->name('logout');
    Route::get('/home', [App\Http\Controllers\Admin\HomeController::class, 'index'])->name('home');
    Route::get('/users',[App\Http\Controllers\Admin\UserController::class, 'users'])->name('users');
    Route::get('/change-status/{uuid}/{status}',[App\Http\Controllers\Admin\UserController::class, 'change_status'])->name('changeStatus');
    Route::get('/change-verify-status/{uuid}/{verify}',[App\Http\Controllers\Admin\UserController::class, 'change_verify_status'])->name('verifyUser');
    Route::get('/user-posts/{uuid}',[App\Http\Controllers\Admin\UserController::class, 'user_posts'])->name('userPosts');
    Route::get('/user-penpals/{uuid}',[App\Http\Controllers\Admin\UserController::class, 'user_penpals'])->name('userPenpals');
    Route::get('/remove-user-post/{user_id}/{post_id}/{post_status}',[App\Http\Controllers\Admin\UserController::class, 'remove_user_post'])->name('removeUserPost');

    Route::get('/posts/create', [\App\Http\Controllers\Admin\PostController::class, 'create'])->name('posts.create');
    Route::post('/posts', [\App\Http\Controllers\Admin\PostController::class, 'store'])->name('posts.store');
    Route::get('/posts',[App\Http\Controllers\Admin\PostController::class, 'index'])->name('posts.index');
    Route::get('/posts/{postId}/edit', [\App\Http\Controllers\Admin\PostController::class, 'edit'])->name('posts.edit');
    Route::put('/posts/{postId}/update', [\App\Http\Controllers\Admin\PostController::class, 'update'])->name('posts.update');
    Route::delete('/posts/{postId}/delete', [\App\Http\Controllers\Admin\PostController::class, 'destroy'])->name('posts.destroy');
 
    Route::get('/upload-file', [\App\Http\Controllers\Admin\FileController::class, 'createForm'])->name('uploadFile');
    Route::post('/upload-file', [\App\Http\Controllers\Admin\FileController::class, 'fileUpload'])->name('submitUploadFile');
    Route::post('/update-admin-post-info', [\App\Http\Controllers\Admin\FileController::class, 'update_post_info'])->name('updatePostInfo');

    Route::get('/upload-tip', [\App\Http\Controllers\Admin\FileController::class, 'upload_tip'])->name('uploadTip');
    Route::post('/submit-tip', [\App\Http\Controllers\Admin\FileController::class, 'submit_tip'])->name('submitUploadTip');

    Route::get('/get-user-transactions', [\App\Http\Controllers\Admin\UserController::class, 'get_user_transactions'])->name('userTransactions');
    Route::get('/get-quick-text', [\App\Http\Controllers\Admin\UserController::class, 'get_quick_text'])->name('quickText');

    Route::get('/prompts', [\App\Http\Controllers\Admin\PromptController::class, 'index'])->name('prompts');
    Route::post('/prompts', [\App\Http\Controllers\Admin\PromptController::class, 'store'])->name('createPrompts');
    Route::delete('/prompts/{id}', [\App\Http\Controllers\Admin\PromptController::class, 'destroy'])->name('prompts.destroy');

    Route::get('/user-promo-codes', [\App\Http\Controllers\Admin\UserController::class, 'get_user_promos'])->name('userPromoCodes');
    Route::post('/create-promo-code', [\App\Http\Controllers\Admin\UserController::class, 'create_user_promo'])->name('createUserPromoCode');
    Route::post('/create-quick-text', [\App\Http\Controllers\Admin\UserController::class, 'create_quick_text'])->name('createQuickText');
    Route::get('/edit-promo/{id}', [\App\Http\Controllers\Admin\UserController::class, 'edit_user_promo'])->name('editUserPromoCode');
    Route::post('/update-promo', [\App\Http\Controllers\Admin\UserController::class, 'update_user_promo'])->name('updateUserPromoCode');
    Route::get('/delete-promo/{id}', [\App\Http\Controllers\Admin\UserController::class, 'delete_user_promo'])->name('deleteUserPromoCode');

    Route::get('/tags', [\App\Http\Controllers\Admin\FileController::class,'post_tags'])->name('postTags');
    Route::post('/submit-tag', [\App\Http\Controllers\Admin\FileController::class,'submit_post_tag'])->name('submitPostTag');
    Route::get('/delete-tag/{uuid}', [\App\Http\Controllers\Admin\FileController::class,'delete_post_tag'])->name('deletePostTag');

    Route::get('/genres', [\App\Http\Controllers\Admin\GenreController::class,'index'])->name('genres.index');
    Route::post('/genres', [\App\Http\Controllers\Admin\GenreController::class,'store'])->name('genres.store');
    Route::get('/genres/{uuid}/delete', [\App\Http\Controllers\Admin\GenreController::class,'destroy'])->name('genres.destroy');

    Route::get('/delete-video/{id}', [App\Http\Controllers\Admin\FileController::class,'destroy_video'])->name('video.destory');
    Route::get('/delete-tip/{id}', [App\Http\Controllers\Admin\FileController::class,'destroy_tip'])->name('tip.destory');

    Route::get('/report-notifications',[App\Http\Controllers\Admin\ReportController::class, 'index'])->name('report-notifications.index');
});

resources/views/admin/file_upload.blade.php
@extends('admin.layouts.main')

@section('title')
    FileUpload
@endsection
@push('style')
    <style>
    .container {
    max-width: 500px;
    }
    dl, ol, ul {
    margin: 0;
    padding: 0;
    list-style: none;
    }
    </style>

@endpush

@section('content')
    <script src="https://cdn.ckeditor.com/4.13.0/standard/ckeditor.js"></script>

    <div class="container mt-5">
        <form action="{{route('admin.submitUploadFile')}}" method="post" enctype="multipart/form-data">
            <input type="hidden" name="file_extension" id="FileExtension" value="">
            <h3 class="text-center mb-5">Upload File </h3>
            @csrf
{{--            @if ($message = Session::get('success'))--}}
{{--                <div class="alert alert-success">--}}
{{--                    <strong>{{ $message }}</strong>--}}
{{--                </div>--}}
{{--            @endif--}}

{{--            @if (count($errors) > 0)--}}
{{--                <div class="alert alert-danger">--}}
{{--                    <ul>--}}
{{--                        @foreach ($errors->all() as $error)--}}
{{--                            <li>{{ $error }}</li>--}}
{{--                        @endforeach--}}
{{--                    </ul>--}}
{{--                </div>--}}
{{--            @endif--}}
            <div class="alert alert-success alert-block" id="responseMsg" style="display: none">
                <button type="button" class="close" data-dismiss="alert">×</button>
                <strong></strong>
            </div>

            <center class="mb-2">

                <img src="" class="myImage" width="320" height="240" style="display: none">
            <video  id="video_p" class="myVideo"  width="320" height="240" controls style="display: none">
                <source src="" type="video/mp4">
            </video>
            </center>
            <div class="custom-file">
                <input type="file" name="file" class="custom-file-input" id="chooseFile" onchange="readFile(this)">
                <label class="custom-file-label file-label" for="chooseFile">Select file</label>
            </div>
            <select name="video_type" class="form-control mt-3 mb-3" style="border: 1px solid grey;">
                <option selected disabled>Select File Type</option>
                <option value="pro">Pro Tips</option>
                <option value="basic">Basic</option>
            </select>

            <select class="category related-post form-control select mt-3" name="post_tags[]" multiple>
                @if(sizeof(@$tags))
                    @foreach(@$tags as $t=>$t_row)
                        <option value="{{@$t_row->uuid}}">{{@$t_row->tag_name}}</option>
                    @endforeach
                @endif
            </select>

            <button type="submit" name="submit" class="btn btn-primary btn-block mt-4">
                Upload Files
            </button>


        </form>
    </div>

    <div class="row videoParentRow">
        @if(sizeof($admin_posts) > 0)
            @foreach($admin_posts as $v => $row)
                <div class="col-md-4 ">
                    <div class="video-container">
                        @if(@$row->file_type == 'image')
                            <img src="{{asset('storage/'.@$row->file)}}"  style="opacity: 1; width: 320px;height: 211px;margin-bottom: 4px; margin-top: 29px;">

                        @elseif(@$row->file_type == 'video')
                            <video width="320" height="240" controls>
                                <source src="{{asset('storage/'.@$row->file)}}" type="video/mp4">
                                <source src="movie.ogg" type="video/ogg">
                                Your browser does not support the video tag.
                            </video>
                        @endif
                        <a href="{{route('admin.video.destory',[@$row->uuid])}}" class="btn btn-danger" style="width:320px"  id="deleteVideoBtn" ><i class="mdi mdi-delete"></i>Delete</a>
                        <a href="" class="btn btn-success mt-2" style="width:320px" data-toggle="modal" data-target="#exampleModal-{{$v}}"  id="" >Add Info</a>

                                <!-- Modal -->
                                <div class="modal fade" id="exampleModal-{{$v}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                    <div class="modal-dialog" role="document">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                        <h5 class="modal-title" id="exampleModalLabel">Post Information</h5>
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                        </div>
                                        <form action="{{route('admin.updatePostInfo')}}" method="post">
                                            @csrf
                                            <input type="hidden" name="post_id" value="{{@$row->uuid}}">
                                            <div class="modal-body">

                                                <div class="form-group">
                                                    {{-- <label for="exampleInputEmail1">Title</label> --}}
                                                    <input type="text" class="form-control" name="title" placeholder="Title" value="{{@$row->title}}">
                                                </div>
                                                <textarea class="ckeditor" id="editor{{$v}}" name="description">{{@$row->description}}</textarea>

                                            </div>
                                            <div class="modal-footer">
                                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                                <button type="submit" class="btn btn-primary">Save changes</button>
                                            </div>
                                        </form>

                                    </div>
                                    </div>
                                </div>
                    </div>
                </div>
                <script>
                    $('.ckeditor').each( function () {

                        CKEDITOR.replace( this.id , {



                        });
                        CKEDITOR.on( 'instanceReady', function( evt )
                        {
                            var editor = evt.editor;

                            editor.on('change', function (e) {
                                var contentSpace = editor.ui.space('contents');
                                var ckeditorFrameCollection = contentSpace.$.getElementsByTagName('iframe');
                                var ckeditorFrame = ckeditorFrameCollection[0];
                                var innerDoc = ckeditorFrame.contentDocument;
                                var innerDocTextAreaHeight = $(innerDoc.body).height();
                                console.log(innerDocTextAreaHeight);
                            });
                        });
                    });

                </script>
            @endforeach
        @endif
    </div>

@endsection
@push('js')

<script type="text/javascript">

    function readFile(input) {
         let reader;
        let isImageExt = true;
        let isVideoExt = true;
        let  validImageExtensions = ["jpg","pdf","jpeg","gif","png"];
        let  validVideoExtensions = ["mp4"];
        $('#FileExtension').val('');
        if (input.files && input.files[0]) {
           let file_ext = input.files[0].name.split('.').pop().toLowerCase();
           if (validImageExtensions.indexOf(file_ext) == -1){
               isImageExt = false;
           }
           if (validVideoExtensions.indexOf(file_ext) == -1){
               isVideoExt = false;
           }

            console.log('---------------Is Video --------------')
            console.log(isVideoExt)
            console.log('---------------Is Image --------------')
            console.log(isImageExt)

            if (isImageExt == true){
                reader = new FileReader();
                reader.onload = function(e) {
                    $('#FileExtension').val('image');
                    $('.myVideo').hide();
                    $('.myImage').show();
                    $('.myImage').attr('src', e.target.result);
                    $('.myImage').css('opacity', 1);
                    $('.file-label').text(input.files[0].name)
                };
                reader.readAsDataURL(input.files[0]);

            }

           if (isVideoExt == true){
               reader = new FileReader();
               reader.onload = function(e) {
                   $('#FileExtension').val('video');
                   $('.myImage').hide();
                   $('.myVideo').show();
                   $('.myVideo').attr('src', e.target.result);
                   $('.file-label').text(input.files[0].name)
               };
               reader.readAsDataURL(input.files[0]);

           }


        }
    }

    // $(document).on('click','#deleteVideoBtn',function (e){
    //
    //
    //     if(!confirm("Do you really want to do this?")) {
    //         return false;
    //     }
    //     e.preventDefault()
    //     //
    //     // let video_id = $(this).attr('videoable_id');
    //     // let video_type = $(this).attr('videoable_type');
    //
    //     var id = $(this).data("id");
    //     // var id = $(this).attr('data-id');
    //
    //     var key = $(this).attr('key_index')
    //     var token = $("meta[name='csrf-token']").attr("content");
    //     var url = e.target;
    //     console.log(id)
    //     $.ajax(
    //         {
    //             url: url.href, //or you can use url: "company/"+id,
    //             type: 'DELETE',
    //             data: {
    //                 id: id,
    //                 _token: token
    //             },
    //             success: function (response){
    //                 if (response.success == true){
    //                     $("#responseMsg").html(response.message)
    //                         location.reload()
    //                 }
    //
    //             }
    //         });
    //     return false;
    //
    //
    //
    //
    // });

</script>
<script type="text/javascript">
    $(document).ready(function() {
        $('.category').select2(
            {
                placeholder:"Select Tags",
                allowClear: true
            }
        );


    });
</script>

@endpush

resources/views/admin/genres.blade.php
@extends('admin.layouts.main')

@section('title')
    Genres
@endsection

@section('content')


    <button type="button" class="btn btn-primary btn-sm float-right m-3" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample" id="addNewBtn"> Add New </button>
    <div class="col-lg-12 grid-margin stretch-card collapse" id="collapseExample">
        <div class="card">
            <div class="card-header">
                Add Genre
            </div>
            <div class="card-body">
                <form id="addNewGenreForm" action="{{route('admin.genres.store')}}" method="POST">
                    @csrf
                    <label>Genre Name</label>
                    <input type="text" name="genres" class="form-control genres" >
                    <input type="button" name="add_genre" class="btn btn-primary btn-sm mt-3 float-right" id="submitGenreBtn" value="Submit">
                </form>
            </div>
        </div>
    </div>
    <div class="col-lg-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Genres Table</h4>
                {{--                <p class="card-description">--}}
                {{--                    Add class <code>.table</code>--}}
                {{--                </p>--}}
                <div class="table-responsive">
                    <table class="table table-striped selfDataTable">
                        <thead>
                        <tr>
                            <th>#</th>
                            <th>Genre Name</th>
                            <th>Created At</th>
                            <th>Action</th>
                        </tr>
                        </thead>
                        <tbody>
                        @if(sizeof($genres)> 0)
                            @foreach($genres as $t => $t_row)
                                <tr>
                                    <td class="py-1">
                                        {{$t+1}}
                                    </td>

                                    <td>{{@$t_row->genres}}</td>
                                    <td>{{\Carbon\Carbon::parse(@$t_row->created_at)->format('d-m-Y')}}</td>
                                    <td><a href="{{route('admin.genres.destroy',['uuid'=>$t_row->uuid])}}"><span class="mdi mdi-delete" style="color: red">Delete</span></a></td>
                                </tr>
                            @endforeach
                        @endif
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

@endsection

@push('js')
<script type="text/javascript">
    $(document).on('click','#submitGenreBtn',function (e){
        e.preventDefault();
       let genreName = $('.genres').val();
       if (genreName != ''){

           $('#addNewGenreForm').submit();
       }else{
           alert('Please Enter Genre Name');
       }

    })
</script>

@endpush

resources/views/admin/tags.blade.php
@extends('admin.layouts.main')

@section('title')
    Tags
@endsection

@section('content')


    <button type="button" class="btn btn-primary btn-sm float-right m-3" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample" id="addNewBtn"> Add New </button>
    <div class="col-lg-12 grid-margin stretch-card collapse" id="collapseExample">
        <div class="card">
            <div class="card-header">
                Add Tag
            </div>
            <div class="card-body">
                <form id="addNewTagForm" action="{{route('admin.submitPostTag')}}" method="POST">
                    @csrf
                    <label>Tag Name</label>
                    <input type="text" name="tag_name" class="form-control tag_name" >
                    <input type="button" name="add_tag" class="btn btn-primary btn-sm mt-3 float-right" id="submitTagBtn" value="Submit">
                </form>
            </div>
        </div>
    </div>
    <div class="col-lg-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Tags Table</h4>
                {{--                <p class="card-description">--}}
                {{--                    Add class <code>.table</code>--}}
                {{--                </p>--}}
                <div class="table-responsive">
                    <table class="table table-striped selfDataTable">
                        <thead>
                        <tr>
                            <th>#</th>
                            <th>Tag Name</th>
                            <th>Created At</th>
                            <th>Action</th>
                        </tr>
                        </thead>
                        <tbody>
                        @if(sizeof($tags)> 0)
                            @foreach($tags as $t => $t_row)
                                <tr>
                                    <td class="py-1">
                                        {{$t+1}}
                                    </td>

                                    <td>{{@$t_row->tag_name}}</td>
                                    <td>{{\Carbon\Carbon::parse(@$t_row->created_at)->format('d-m-Y')}}</td>
                                    <td><a href="{{route('admin.deletePostTag',['uuid'=>$t_row->uuid])}}"><span class="mdi mdi-delete" style="color: red">Delete</span></a></td>
                                </tr>
                            @endforeach
                        @endif
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

@endsection

@push('js')
<script type="text/javascript">
    $(document).on('click','#submitTagBtn',function (e){
        e.preventDefault();
       let tagName = $('.tag_name').val();
       if (tagName != ''){

           $('#addNewTagForm').submit();
       }else{
           alert('Please Enter Tag Name');
       }

    })
</script>

@endpush

resources/views/admin/tip_upload.blade.php
@extends('admin.layouts.main')

@section('title')
    FileUpload
@endsection
@push('style')
    <style>
    .container {
    max-width: 500px;
    }
    dl, ol, ul {
    margin: 0;
    padding: 0;
    list-style: none;
    }
    </style>

@endpush

@section('content')
    <div class="container mt-5">
        <form action="{{route('admin.submitUploadTip')}}" method="post" enctype="multipart/form-data">
            <input type="hidden" name="file_extension" id="FileExtension" value="">
            <h3 class="text-center mb-5">Upload File </h3>
            @csrf
{{--            @if ($message = Session::get('success'))--}}
{{--                <div class="alert alert-success">--}}
{{--                    <strong>{{ $message }}</strong>--}}
{{--                </div>--}}
{{--            @endif--}}

{{--            @if (count($errors) > 0)--}}
{{--                <div class="alert alert-danger">--}}
{{--                    <ul>--}}
{{--                        @foreach ($errors->all() as $error)--}}
{{--                            <li>{{ $error }}</li>--}}
{{--                        @endforeach--}}
{{--                    </ul>--}}
{{--                </div>--}}
{{--            @endif--}}
            <div class="alert alert-success alert-block" id="responseMsg" style="display: none">
                <button type="button" class="close" data-dismiss="alert">×</button>
                <strong></strong>
            </div>

            <center class="mb-2">

                <img src="" class="myImage" width="320" height="240" style="display: none">
            <video  id="video_p" class="myVideo"  width="320" height="240" controls style="display: none">
                <source src="" type="video/mp4">
            </video>
            </center>
            <div class="custom-file">
                <input type="file" name="file" class="custom-file-input" id="chooseFile" onchange="readFile(this)">
                <label class="custom-file-label file-label" for="chooseFile">Select file</label>
            </div>




            <button type="submit" name="submit" class="btn btn-primary btn-block mt-4">
                Upload Files
            </button>


        </form>
    </div>

    <div class="row videoParentRow">
        @if(sizeof($admin_tips) > 0)
            @foreach($admin_tips as $v => $row)
                <div class="col-md-4 ">
                    <div class="video-container">
                        @if(@$row->file_type == 'image')
                            <img src="{{asset('storage/'.@$row->file)}}"  style="opacity: 1; width: 320px;height: 211px;margin-bottom: 4px; margin-top: 29px;">

                        @elseif(@$row->file_type == 'video')
                            <video width="320" height="240" controls>
                                <source src="{{asset('storage/'.@$row->file)}}" type="video/mp4">
                                <source src="movie.ogg" type="video/ogg">
                                Your browser does not support the video tag.
                            </video>
                        @endif
                        <a href="{{route('admin.tip.destory',[@$row->uuid])}}"  id="deleteVideoBtn" class="btn btn-danger" style="width:320px"  ><i class="mdi mdi-delete"></i>Delete</a>
                    </div>
                </div>
            @endforeach
        @endif
    </div>

@endsection
@push('js')

<script type="text/javascript">

    function readFile(input) {
         let reader;
        let isImageExt = true;
        let isVideoExt = true;
        let  validImageExtensions = ["jpg","pdf","jpeg","gif","png"];
        let  validVideoExtensions = ["mp4"];
        $('#FileExtension').val('');
        if (input.files && input.files[0]) {
           let file_ext = input.files[0].name.split('.').pop().toLowerCase();
           if (validImageExtensions.indexOf(file_ext) == -1){
               isImageExt = false;
           }
           if (validVideoExtensions.indexOf(file_ext) == -1){
               isVideoExt = false;
           }

            console.log('---------------Is Video --------------')
            console.log(isVideoExt)
            console.log('---------------Is Image --------------')
            console.log(isImageExt)

            if (isImageExt == true){
                reader = new FileReader();
                reader.onload = function(e) {
                    $('#FileExtension').val('image');
                    $('.myVideo').hide();
                    $('.myImage').show();
                    $('.myImage').attr('src', e.target.result);
                    $('.myImage').css('opacity', 1);
                    $('.file-label').text(input.files[0].name)
                };
                reader.readAsDataURL(input.files[0]);

            }

           if (isVideoExt == true){
               reader = new FileReader();
               reader.onload = function(e) {
                   $('#FileExtension').val('video');
                   $('.myImage').hide();
                   $('.myVideo').show();
                   $('.myVideo').attr('src', e.target.result);
                   $('.file-label').text(input.files[0].name)
               };
               reader.readAsDataURL(input.files[0]);

           }


        }
    }

    // $(document).on('click','#deleteVideoBtn',function (e){
    //
    //
    //     if(!confirm("Do you really want to do this?")) {
    //         return false;
    //     }
    //     e.preventDefault()
    //     //
    //     // let video_id = $(this).attr('videoable_id');
    //     // let video_type = $(this).attr('videoable_type');
    //
    //     var id = $(this).data("id");
    //     // var id = $(this).attr('data-id');
    //
    //     // var key = $(this).attr('key_index')
    //     var token = $("meta[name='csrf-token']").attr("content");
    //     var url = e.target;
    //     console.log(id)
    //     $.ajax(
    //         {
    //             url: url.href, //or you can use url: "company/"+id,
    //             type: 'DELETE',
    //             data: {
    //                 id: id,
    //                 _token: token
    //             },
    //             success: function (response){
    //                 if (response.success == true){
    //                     $("#responseMsg").html(response.message)
    //                         location.reload()
    //                 }
    //
    //             }
    //         });
    //     return false;
    //
    //
    //
    //
    // });

</script>


@endpush