routes/web.php
<?php

use App\Http\Controllers\Admin\AuthController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Hash;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/login', function () {
//    return view('welcome');
    return redirect('/admin/login');
});
Route::get('/', function () {
//    return view('welcome');
    return redirect('/admin/login');
});
Route::get('/password',function (){
   echo Hash::make('12345678');
});
//Auth::routes(['register' => false,
//    'reset'=>false,
//    'remember'=> false]);


//Route::group(['middleware'=> 'auth'], function(){
Route::get('/accept-payment/{id}',[\App\Http\Controllers\PaymentController::class,'accept_payment']);
Route::get('/cancel-payment/{id}',[\App\Http\Controllers\PaymentController::class,'cancel_payment']);
Route::get('/payment-view',function (){
    return view('payment_response');
});

Route::get('/contact-us',function (){
    return view('users.contact_us');
});

Route::get('/clear', function () {
    Artisan::call('optimize');
});


Route::get('admin/login',[AuthController::class,'showLoginForm'])->name('admin.login');
Route::post('admin/login',[AuthController::class,'login']);
Route::prefix('/admin')->name('admin.')->namespace('Admin')->middleware('auth:admin')->group(function(){
    Route::post('/logout',[AuthController::class,'logout'])->name('logout');
    Route::get('/home', [App\Http\Controllers\Admin\HomeController::class, 'index'])->name('home');
    Route::get('/users',[App\Http\Controllers\Admin\UserController::class, 'users'])->name('users');
    Route::get('/change-status/{uuid}/{status}',[App\Http\Controllers\Admin\UserController::class, 'change_status'])->name('changeStatus');
    Route::get('/change-verify-status/{uuid}/{verify}',[App\Http\Controllers\Admin\UserController::class, 'change_verify_status'])->name('verifyUser');
    Route::get('/user-posts/{uuid}',[App\Http\Controllers\Admin\UserController::class, 'user_posts'])->name('userPosts');
    Route::get('/user-penpals/{uuid}',[App\Http\Controllers\Admin\UserController::class, 'user_penpals'])->name('userPenpals');
    Route::get('/remove-user-post/{user_id}/{post_id}/{post_status}',[App\Http\Controllers\Admin\UserController::class, 'remove_user_post'])->name('removeUserPost');

    Route::get('/posts/create', [\App\Http\Controllers\Admin\PostController::class, 'create'])->name('posts.create');
    Route::post('/posts', [\App\Http\Controllers\Admin\PostController::class, 'store'])->name('posts.store');
    Route::get('/posts',[App\Http\Controllers\Admin\PostController::class, 'index'])->name('posts.index');
    Route::get('/posts/{postId}/edit', [\App\Http\Controllers\Admin\PostController::class, 'edit'])->name('posts.edit');
    Route::put('/posts/{postId}/update', [\App\Http\Controllers\Admin\PostController::class, 'update'])->name('posts.update');
    Route::delete('/posts/{postId}/delete', [\App\Http\Controllers\Admin\PostController::class, 'destroy'])->name('posts.destroy');
 
    Route::get('/upload-file', [\App\Http\Controllers\Admin\FileController::class, 'createForm'])->name('uploadFile');
    Route::post('/upload-file', [\App\Http\Controllers\Admin\FileController::class, 'fileUpload'])->name('submitUploadFile');
    Route::post('/update-admin-post-info', [\App\Http\Controllers\Admin\FileController::class, 'update_post_info'])->name('updatePostInfo');

    Route::get('/upload-tip', [\App\Http\Controllers\Admin\FileController::class, 'upload_tip'])->name('uploadTip');
    Route::post('/submit-tip', [\App\Http\Controllers\Admin\FileController::class, 'submit_tip'])->name('submitUploadTip');

    Route::get('/get-user-transactions', [\App\Http\Controllers\Admin\UserController::class, 'get_user_transactions'])->name('userTransactions');
    Route::get('/get-quick-text', [\App\Http\Controllers\Admin\UserController::class, 'get_quick_text'])->name('quickText');

    Route::get('/prompts', [\App\Http\Controllers\Admin\PromptController::class, 'index'])->name('prompts');
    Route::post('/prompts', [\App\Http\Controllers\Admin\PromptController::class, 'store'])->name('createPrompts');
    Route::delete('/prompts/{id}', [\App\Http\Controllers\Admin\PromptController::class, 'destroy'])->name('prompts.destroy');

    Route::get('/user-promo-codes', [\App\Http\Controllers\Admin\UserController::class, 'get_user_promos'])->name('userPromoCodes');
    Route::post('/create-promo-code', [\App\Http\Controllers\Admin\UserController::class, 'create_user_promo'])->name('createUserPromoCode');
    Route::post('/create-quick-text', [\App\Http\Controllers\Admin\UserController::class, 'create_quick_text'])->name('createQuickText');
    Route::get('/edit-promo/{id}', [\App\Http\Controllers\Admin\UserController::class, 'edit_user_promo'])->name('editUserPromoCode');
    Route::post('/update-promo', [\App\Http\Controllers\Admin\UserController::class, 'update_user_promo'])->name('updateUserPromoCode');
    Route::get('/delete-promo/{id}', [\App\Http\Controllers\Admin\UserController::class, 'delete_user_promo'])->name('deleteUserPromoCode');

    Route::get('/tags', [\App\Http\Controllers\Admin\FileController::class,'post_tags'])->name('postTags');
    Route::post('/submit-tag', [\App\Http\Controllers\Admin\FileController::class,'submit_post_tag'])->name('submitPostTag');
    Route::get('/delete-tag/{uuid}', [\App\Http\Controllers\Admin\FileController::class,'delete_post_tag'])->name('deletePostTag');

    Route::get('/genres', [\App\Http\Controllers\Admin\GenreController::class,'index'])->name('genres.index');
    Route::post('/genres', [\App\Http\Controllers\Admin\GenreController::class,'store'])->name('genres.store');
    Route::get('/genres/{uuid}/delete', [\App\Http\Controllers\Admin\GenreController::class,'destroy'])->name('genres.destroy');

    Route::get('/delete-video/{id}', [App\Http\Controllers\Admin\FileController::class,'destroy_video'])->name('video.destory');
    Route::get('/delete-tip/{id}', [App\Http\Controllers\Admin\FileController::class,'destroy_tip'])->name('tip.destory');

    Route::get('/report-notifications',[App\Http\Controllers\Admin\ReportController::class, 'index'])->name('report-notifications.index');
});

resources/views/admin/partials/footer.blade.php
<footer class="footer">
    <div class="d-sm-flex justify-content-center justify-content-sm-between">
        <span class="text-muted text-center text-sm-left d-block d-sm-inline-block">Copyright © 2018 <a href="https://www.urbanui.com/" target="_blank">Urbanui</a>. All rights reserved.</span>
        <span class="float-none float-sm-right d-block mt-1 mt-sm-0 text-center">Hand-crafted & made with <i class="mdi mdi-heart text-danger"></i></span>
    </div>
</footer>

resources/views/admin/partials/head.blade.php
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>
        Writers Talk - @yield('title')
    </title>

    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.0/css/bootstrap.min.css"  />
{{--    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.0/js/bootstrap.min.js" ></script>--}}
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/css/select2.min.css" rel="stylesheet" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/js/select2.min.js" defer></script>
    <!-- plugins:css -->
    <link rel="stylesheet" href="{{asset('template/vendors/mdi/css/materialdesignicons.min.css')}}">
    <link rel="stylesheet" href="{{asset('template/vendors/base/vendor.bundle.base.css')}}">
    <!-- endinject -->
    <!-- plugin css for this page -->
    <link rel="stylesheet" href="{{asset('template/vendors/datatables.net-bs4/dataTables.bootstrap4.css')}}">
    <!-- End plugin css for this page -->
    <!-- inject:css -->
    <link rel="stylesheet" href="{{asset('template/css/style.css')}}">
    <link rel="stylesheet" href="{{asset('css/custom.css')}}">
    <!-- endinject -->
    <link rel="shortcut icon" href="{{asset('template/images/favicon.png')}}" />
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.25/css/jquery.dataTables.css">

resources/views/admin/partials/nav.blade.php
<!-- partial:partials/_navbar.html -->
<nav class="navbar col-lg-12 col-12 p-0 fixed-top d-flex flex-row">
    <div class="navbar-brand-wrapper d-flex justify-content-center">
        <div class="navbar-brand-inner-wrapper d-flex justify-content-between align-items-center w-100">
            <a class="navbar-brand brand-logo" href="{{route('admin.home')}}"><img src="{{asset('template/images/logo.jpeg')}}" alt="logo" style="width: 70px; height: 48px;"></a>
            <a class="navbar-brand brand-logo-mini" href="index.html"><img src="{{asset('template/images/logo-mini.svg')}}" alt="logo"/></a>
            <button class="navbar-toggler navbar-toggler align-self-center" type="button" data-toggle="minimize">
                <span class="mdi mdi-sort-variant"></span>
            </button>
        </div>
    </div>
    <div class="navbar-menu-wrapper d-flex align-items-center justify-content-end">
{{--        <ul class="navbar-nav mr-lg-4 w-100">--}}
{{--            <li class="nav-item nav-search d-none d-lg-block w-100">--}}
{{--                <div class="input-group">--}}
{{--                    <div class="input-group-prepend">--}}
{{--                <span class="input-group-text" id="search">--}}
{{--                  <i class="mdi mdi-magnify"></i>--}}
{{--                </span>--}}
{{--                    </div>--}}
{{--                    <input type="text" class="form-control" placeholder="Search now" aria-label="search" aria-describedby="search">--}}
{{--                </div>--}}
{{--            </li>--}}
{{--        </ul>--}}

        <ul class="navbar-nav navbar-nav-right">
{{--            <li class="nav-item dropdown mr-1">--}}
{{--                <a class="nav-link count-indicator dropdown-toggle d-flex justify-content-center align-items-center" id="messageDropdown" href="#" data-toggle="dropdown">--}}
{{--                    <i class="mdi mdi-message-text mx-0"></i>--}}
{{--                    <span class="count"></span>--}}
{{--                </a>--}}
{{--                <div class="dropdown-menu dropdown-menu-right navbar-dropdown" aria-labelledby="messageDropdown">--}}
{{--                    <p class="mb-0 font-weight-normal float-left dropdown-header">Messages</p>--}}
{{--                    <a class="dropdown-item">--}}
{{--                        <div class="item-thumbnail">--}}
{{--                            <img src="{{asset('template/images/faces/face4.jpg')}}" alt="image" class="profile-pic">--}}
{{--                        </div>--}}
{{--                        <div class="item-content flex-grow">--}}
{{--                            <h6 class="ellipsis font-weight-normal">David Grey--}}
{{--                            </h6>--}}
{{--                            <p class="font-weight-light small-text text-muted mb-0">--}}
{{--                                The meeting is cancelled--}}
{{--                            </p>--}}
{{--                        </div>--}}
{{--                    </a>--}}
{{--                    <a class="dropdown-item">--}}
{{--                        <div class="item-thumbnail">--}}
{{--                            <img src="{{asset('template/images/faces/face2.jpg')}}" alt="image" class="profile-pic">--}}
{{--                        </div>--}}
{{--                        <div class="item-content flex-grow">--}}
{{--                            <h6 class="ellipsis font-weight-normal">Tim Cook--}}
{{--                            </h6>--}}
{{--                            <p class="font-weight-light small-text text-muted mb-0">--}}
{{--                                New product launch--}}
{{--                            </p>--}}
{{--                        </div>--}}
{{--                    </a>--}}
{{--                    <a class="dropdown-item">--}}
{{--                        <div class="item-thumbnail">--}}
{{--                            <img src="{{asset('template/images/faces/face3.jpg')}}" alt="image" class="profile-pic">--}}
{{--                        </div>--}}
{{--                        <div class="item-content flex-grow">--}}
{{--                            <h6 class="ellipsis font-weight-normal"> Johnson--}}
{{--                            </h6>--}}
{{--                            <p class="font-weight-light small-text text-muted mb-0">--}}
{{--                                Upcoming board meeting--}}
{{--                            </p>--}}
{{--                        </div>--}}
{{--                    </a>--}}
{{--                </div>--}}
{{--            </li>--}}
{{--            <li class="nav-item dropdown mr-4">--}}
{{--                <a class="nav-link count-indicator dropdown-toggle d-flex align-items-center justify-content-center notification-dropdown" id="notificationDropdown" href="#" data-toggle="dropdown">--}}
{{--                    <i class="mdi mdi-bell mx-0"></i>--}}
{{--                    <span class="count"></span>--}}
{{--                </a>--}}
{{--                <div class="dropdown-menu dropdown-menu-right navbar-dropdown" aria-labelledby="notificationDropdown">--}}
{{--                    <p class="mb-0 font-weight-normal float-left dropdown-header">Notifications</p>--}}
{{--                    <a class="dropdown-item">--}}
{{--                        <div class="item-thumbnail">--}}
{{--                            <div class="item-icon bg-success">--}}
{{--                                <i class="mdi mdi-information mx-0"></i>--}}
{{--                            </div>--}}
{{--                        </div>--}}
{{--                        <div class="item-content">--}}
{{--                            <h6 class="font-weight-normal">Application Error</h6>--}}
{{--                            <p class="font-weight-light small-text mb-0 text-muted">--}}
{{--                                Just now--}}
{{--                            </p>--}}
{{--                        </div>--}}
{{--                    </a>--}}
{{--                    <a class="dropdown-item">--}}
{{--                        <div class="item-thumbnail">--}}
{{--                            <div class="item-icon bg-warning">--}}
{{--                                <i class="mdi mdi-settings mx-0"></i>--}}
{{--                            </div>--}}
{{--                        </div>--}}
{{--                        <div class="item-content">--}}
{{--                            <h6 class="font-weight-normal">Settings</h6>--}}
{{--                            <p class="font-weight-light small-text mb-0 text-muted">--}}
{{--                                Private message--}}
{{--                            </p>--}}
{{--                        </div>--}}
{{--                    </a>--}}
{{--                    <a class="dropdown-item">--}}
{{--                        <div class="item-thumbnail">--}}
{{--                            <div class="item-icon bg-info">--}}
{{--                                <i class="mdi mdi-account-box mx-0"></i>--}}
{{--                            </div>--}}
{{--                        </div>--}}
{{--                        <div class="item-content">--}}
{{--                            <h6 class="font-weight-normal">New user registration</h6>--}}
{{--                            <p class="font-weight-light small-text mb-0 text-muted">--}}
{{--                                2 days ago--}}
{{--                            </p>--}}
{{--                        </div>--}}
{{--                    </a>--}}
{{--                </div>--}}
{{--            </li>--}}
            <li class="nav-item nav-profile dropdown">
                <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown" id="profileDropdown">
                    <img src="{{asset('template/images/faces/face5.jpg')}}" alt="profile"/>
                    <span class="nav-profile-name"> {{ Auth::guard('admin')->user()->name  }}  </span>
                </a>
                <div class="dropdown-menu dropdown-menu-right navbar-dropdown" aria-labelledby="profileDropdown">
{{--                    <a class="dropdown-item">--}}
{{--                        <i class="mdi mdi-settings text-primary"></i>--}}
{{--                        Settings--}}
{{--                    </a>--}}
                    <a class="dropdown-item" href="{{ route('admin.logout') }}"
                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">

                        <i class="mdi mdi-logout text-primary"></i>
                        {{ __('Logout') }}
                    </a>
                    <form id="logout-form" action="{{ route('admin.logout') }}" method="POST" class="d-none">
                        @csrf
                    </form>
                </div>
            </li>
        </ul>
        <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button" data-toggle="offcanvas">
            <span class="mdi mdi-menu"></span>
        </button>
    </div>
</nav>

resources/views/admin/partials/response_message.blade.php
@if ($message = Session::get('success'))
    <div class="alert alert-success alert-block">
        <button type="button" class="close" data-dismiss="alert">×</button>
        <strong>{{ $message }}</strong>
    </div>
@endif

@if ($message = Session::get('error'))
    <div class="alert alert-danger alert-block">
        <button type="button" class="close" data-dismiss="alert">×</button>
        <strong>{{ $message }}</strong>
    </div>
@endif

@if ($message = Session::get('warning'))
    <div class="alert alert-warning alert-block">
        <button type="button" class="close" data-dismiss="alert">×</button>
        <strong>{{ $message }}</strong>
    </div>
@endif

@if ($message = Session::get('info'))
    <div class="alert alert-info alert-block">
        <button type="button" class="close" data-dismiss="alert">×</button>
        <strong>{{ $message }}</strong>
    </div>
@endif

@if ($errors->any())
    <div class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert">×</button>
        Check the following errors :(
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

resources/views/admin/partials/scripts.blade.php
<!-- plugins:js -->
<script src="{{asset('template/vendors/base/vendor.bundle.base.js')}}"></script>
<!-- endinject -->
<!-- Plugin js for this page-->
<script src="{{asset('template/vendors/chart.js/Chart.min.js')}}"></script>
{{--<script src="{{asset('template/vendors/datatables.net/jquery.dataTables.js')}}"></script>--}}
{{--<script src="{{asset('template/vendors/datatables.net-bs4/dataTables.bootstrap4.js')}}"></script>--}}
<!-- End plugin js for this page-->
<!-- inject:js -->
<script src="{{asset('template/js/off-canvas.js')}}"></script>
<script src="{{asset('template/js/hoverable-collapse.js')}}"></script>
<script src="{{asset('template/js/template.js')}}"></script>
<!-- endinject -->
<!-- Custom js for this page-->
<script src="{{asset('template/js/dashboard.js')}}"></script>
{{--<script src="{{asset('template/js/data-table.js')}}"></script>--}}
{{--<script src="{{asset('template/js/jquery.dataTables.js')}}"></script>--}}
{{--<script src="{{asset('template/js/dataTables.bootstrap4.js')}}"></script>--}}

<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.25/js/jquery.dataTables.js"></script>

<!-- End custom js for this page-->
@stack('js')

resources/views/admin/partials/sidebar.blade.php
<nav class="sidebar sidebar-offcanvas" id="sidebar">
    <ul class="nav">
        <li class="nav-item {{(request()->is('home*')) ? 'active': ''}}">
            <a class="nav-link" href="{{route('admin.home')}}">
                <i class="mdi mdi-home menu-icon"></i>
                <span class="menu-title">Dashboard</span>
            </a>
        </li>

        <li class="nav-item">
            <a class="nav-link" href="{{route('admin.users')}}">
                <i class="mdi mdi-account menu-icon"></i>
                <span class="menu-title">Users</span>
            </a>
        </li>

        <li class="nav-item">
            <a class="nav-link" href="{{route('admin.posts.index')}}">
                <i class="mdi mdi-upload menu-icon"></i>
                <span class="menu-title">Posts</span>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{{route('admin.report-notifications.index')}}">
                <i class="mdi mdi-upload menu-icon"></i>
                <span class="menu-title">Report Notifications</span>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{{route('admin.uploadFile')}}">
                <i class="mdi mdi-upload menu-icon"></i>
                <span class="menu-title">Old Posts</span>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{{route('admin.uploadTip')}}">
                <i class="mdi mdi-autorenew menu-icon"></i>
                <span class="menu-title">Tips</span>
            </a>
        </li>

        <li class="nav-item">
            <a class="nav-link" href="{{route('admin.quickText')}}">
                <i class="mdi mdi-text menu-icon"></i>
                <span class="menu-title">Quicks Text</span>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{{route('admin.prompts')}}">
                <i class="mdi mdi-text menu-icon"></i>
                <span class="menu-title">Prompts</span>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{{route('admin.userTransactions')}}">
                <i class="mdi mdi-transfer menu-icon"></i>
                <span class="menu-title">Transactions</span>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{{route('admin.userPromoCodes')}}">
                <i class="mdi mdi-ticket-account menu-icon"></i>
                <span class="menu-title">Promo Codes</span>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{{route('admin.postTags')}}">
                <i class="mdi mdi-tag-multiple menu-icon"></i>
                <span class="menu-title">Tags</span>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{{route('admin.genres.index')}}">
                <i class="mdi mdi-tag-multiple menu-icon"></i>
                <span class="menu-title">Genres</span>
            </a>
        </li>

{{--        <li class="nav-item">--}}
{{--            <a class="nav-link" data-toggle="collapse" href="#ui-basic" aria-expanded="false" aria-controls="ui-basic">--}}
{{--                <i class="mdi mdi-circle-outline menu-icon"></i>--}}
{{--                <span class="menu-title">UI Elements</span>--}}
{{--                <i class="menu-arrow"></i>--}}
{{--            </a>--}}
{{--            <div class="collapse" id="ui-basic">--}}
{{--                <ul class="nav flex-column sub-menu">--}}
{{--                    <li class="nav-item"> <a class="nav-link" href="pages/ui-features/buttons.html">Buttons</a></li>--}}
{{--                    <li class="nav-item"> <a class="nav-link" href="pages/ui-features/typography.html">Typography</a></li>--}}
{{--                </ul>--}}
{{--            </div>--}}
{{--        </li>--}}
{{--        <li class="nav-item">--}}
{{--            <a class="nav-link" href="pages/forms/basic_elements.html">--}}
{{--                <i class="mdi mdi-view-headline menu-icon"></i>--}}
{{--                <span class="menu-title">Form elements</span>--}}
{{--            </a>--}}
{{--        </li>--}}
{{--        <li class="nav-item">--}}
{{--            <a class="nav-link" href="pages/charts/chartjs.html">--}}
{{--                <i class="mdi mdi-chart-pie menu-icon"></i>--}}
{{--                <span class="menu-title">Charts</span>--}}
{{--            </a>--}}
{{--        </li>--}}
{{--        <li class="nav-item">--}}
{{--            <a class="nav-link" href="pages/tables/basic-table.html">--}}
{{--                <i class="mdi mdi-grid-large menu-icon"></i>--}}
{{--                <span class="menu-title">Tables</span>--}}
{{--            </a>--}}
{{--        </li>--}}

{{--        <li class="nav-item">--}}
{{--            <a class="nav-link" data-toggle="collapse" href="#auth" aria-expanded="false" aria-controls="auth">--}}
{{--                <i class="mdi mdi-account menu-icon"></i>--}}
{{--                <span class="menu-title">User Pages</span>--}}
{{--                <i class="menu-arrow"></i>--}}
{{--            </a>--}}
{{--            <div class="collapse" id="auth">--}}
{{--                <ul class="nav flex-column sub-menu">--}}
{{--                    <li class="nav-item"> <a class="nav-link" href="pages/samples/login.html"> Login </a></li>--}}
{{--                    <li class="nav-item"> <a class="nav-link" href="pages/samples/login-2.html"> Login 2 </a></li>--}}
{{--                    <li class="nav-item"> <a class="nav-link" href="pages/samples/register.html"> Register </a></li>--}}
{{--                    <li class="nav-item"> <a class="nav-link" href="pages/samples/register-2.html"> Register 2 </a></li>--}}
{{--                    <li class="nav-item"> <a class="nav-link" href="pages/samples/lock-screen.html"> Lockscreen </a></li>--}}
{{--                </ul>--}}
{{--            </div>--}}
{{--        </li>--}}
{{--        <li class="nav-item">--}}
{{--            <a class="nav-link" href="documentation/documentation.html">--}}
{{--                <i class="mdi mdi-file-document-box-outline menu-icon"></i>--}}
{{--                <span class="menu-title">Documentation</span>--}}
{{--            </a>--}}
{{--        </li>--}}
    </ul>
</nav>